### ISSUE TITLE
Ways to reduce source json file size

### ISSUE THREAD

**Issue by khokm** [openapistack/openapi-client-axios#176]
This is not bug report of feature request, i'm asking for helper tool.

I'm using the following schema:
```ts
import { Client } from "./client"; //generated client types
import definition from "./openapi.json";
new OpenAPIClientAxios({ definition: definition as any, axiosConfigDefaults }).initSync<Client>();
```
So the `openapi.json` will also be included in resulting bundle.
The problem here is that this file can be too large because of `summary` comments, descriptions, examples, etc).
Is there any way to make this file more 'clean', leaving only information which will be actually used by codegen?

**Comment by anttiviljami** [comment]
Yes! Use `openapicmd read --json --strip openapi-client-axios > openapi-runtime.json` to get rid of all the unnecessary metadata.
